baseURL = "https://static-website.com/"
languageCode = "en-us"
title = "Static Website"
author = "Nickolas Kraus"
canonifyurls = true
theme = "black-and-light-2"

pygmentsStyle       = "tango"
pygmentsCodeFences  = true

googleAnalytics = ""

[params]
  siteName = "Static Website"
  dateFormat = "January 2, 2006"

[[menu.main]]
    name = "About"
    url  = "/about"
[[menu.main]]
    name = "Articles"
    url  = "/articles"
